insert into user values ('AntonisNikos', 'ablaoublas');
insert into song(title, lyrics, chords) values ('These Trees', 'Lyrics for These Trees', 'Dm  C Dm');
insert into song(title, lyrics, public) values ('Margharet', 'Peristeri in the sky',  1);
insert into song(title, chords, lyrics) values ('A day in life', 'Dm  F', 'Lyrics for a day in life');
insert into composer values('Theodorakis');
insert into composer values('Lennon');
insert into composer values('MacCartney');
insert into lyricist values('Theodorakis');
insert into lyricist values('MacCartney');
insert into lyricist values('Lennon');
insert into lyricist values('Ritsos');
insert into wrotelyrics values('Ritsos',1);
insert into wrotemusic values('Theodorakis',1);
insert into wrotemusic values('Theodorakis',2);
insert into wrotelyrics values('Theodorakis',2);
insert into wrotelyrics values('Lennon',3);
insert into wrotemusic values('Lennon',3);
insert into wrotemusic values('MacCartney',3);
insert into wrotelyrics values('MacCartney',3);
